import Head from "next/head";
import React, { useState } from "react";
import {
  ChakraProvider,
  extendTheme,
  Container,
  Heading,
  Textarea,
  Spacer,
} from "@chakra-ui/react";
import "@fontsource/fira-code";

function any() {
  return `.`;
}

function zeroOrMore(char) {
  return `${char}*`;
}

function oneOrMore(char) {
  return `${char}+`;
}

function range(start, end) {
  return "";
}

function compile(code) {
  try {
    return eval(code);
  } catch (e) {
    return "";
  }
}

const theme = extendTheme({
  styles: {
    global: {
      body: {
        backgroundColor: "#111",
        color: "white",
      },
    },
  },
  fonts: {
    heading: "Open Sans",
    body: "Raleway",
  },
});

export default function Home() {
  const [regex, setRegex] = useState("regex");

  return (
    <ChakraProvider theme={theme}>
      <Head my={"md"}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.md">
        <Heading my={8}>Regex Generator</Heading>
        <Textarea
          placeholder="code"
          fontFamily="Fira Code"
          resize="none"
          onChange={(event) => {
            const value = event.target.value;
            const result = compile(value);
            if (result) {
              setRegex(result);
            }
          }}
        ></Textarea>
        <Spacer height={4} />
        <Textarea
          value={regex}
          readOnly={true}
          fontFamily="Fira Code"
          resize="none"
        ></Textarea>
      </Container>
    </ChakraProvider>
  );
}
